spring:
  application:
    name: review-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.68.12.96:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
#    instanceId: ${spring.application.name}:${random.value}

server:
  port: 8002
